#!/usr/bin/python3

import time
import math
import sys


def pollard_rho_factorization(number):
    if number % 2 == 0:
        return 2

    x = 2
    y = 2
    divisor = 1

    def f(x):
        return (x**2 + 1) % number

    while divisor == 1:
        x = f(x)
        y = f(f(y))
        divisor = math.gcd(abs(x - y), number)

    return divisor


def main():
    if len(sys.argv) != 2:
        print("Usage: python factorizer.py <file>")
        return

    file_path = sys.argv[1]
    try:
        with open(file_path, 'r') as file:
            numbers = file.readlines()

        for line in numbers:
            num = int(line.strip())
            factor = pollard_rho_factorization(num)
            other_factor = num // factor
            print(f"{num} = {other_factor} * {factor}")

            if time.time() - start_time > 5:
                print("Time limit exceeded")
                exit()

    except FileNotFoundError:
        print(f"File '{file_path}' not found.")


if __name__ == '__main__':
    start_time = time.time()
    main()
